### ISSUE TITLE
Enable arm64 builds for sushy-tools container

### ISSUE THREAD

**Issue by e-minguez** [metal3-io/ironic-image#615]
https://quay.io/repository/metal3-io/sushy-tools provides the sushy-tool containerized for easy usage. It would be nice if arm64 builds of that container image can be enabled.

**Comment by e-minguez** [comment]
After reading https://github.com/metal3-io/ironic-image/blob/main/.github/workflows/build-images-action.yml#L29C11-L29C83 & https://github.com/metal3-io/project-infra/blob/main/.github/workflows/container-image-build.yml#L85C13-L85C52 it seems the builds are done by the https://github.com/mr-smithers-excellent/docker-build-push action which seems to support multi-platform builds per https://github.com/mr-smithers-excellent/docker-build-push?tab=readme-ov-file#multi-platform-builds

```
  - uses: mr-smithers-excellent/docker-build-push@v6
    name: Build & push Docker image
    with:
      image: repo/image
      registry: docker.io
      multiPlatform: true
      platform: linux/amd64,linux/arm64,linux/arm/v7
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
```

Probably I'm missing something and it is not that easy 😅
